### ISSUE TITLE
Comments as blockquotes

### ISSUE THREAD

**Issue by volodymyr-kushnir** [SergiiBubalo/bsa-first-lection-homework#3]
Hi. Could you please format your articles' comments with Markdown blockquotes? They'll get grey background and will be more readable that way. You're grand otherwise, keep up the good work.
*P. S. Second contributor — cool, didn't see that coming. 5 points to gryffindor.*

**Comment by sergii-bubalo** [comment]
Hi, Volodymyr! Thanks, it's a good idea. I'll do it.

**Comment by sergii-bubalo** [comment]
Done ...
